import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "../context/AuthContext";
import NavigationBar from "@/components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex">
        <AuthProvider>
        <NavigationBar/>
          <main className="flex min-h-screen flex-col items-center p-24 w-full">          
            {children}
          </main>
        </AuthProvider>
      </body>
    </html>
  );
}
