
export const skillsOptions = [
  { value: "1", label: "Java" },
  { value: "2", label: "Python" },
  { value: "3", label: "JavaScript" },
  { value: "4", label: "TypeScript" },
  { value: "5", label: "C/C++" },
  { value: "6", label: "C#" },
  { value: "7", label: "Ruby" },
  { value: "8", label: "PHP" },
  { value: "9", label: "Swift" },
  { value: "10", label: "Kotlin" },
  { value: "11", label: "Go" },
  { value: "12", label: "Rust" },
  { value: "13", label: "HTML" },
  { value: "14", label: "CSS" },
  { value: "15", label: "SQL" },
  { value: "16", label: "NoSQL" },
  { value: "17", label: "R" },
  { value: "18", label: "Scala" },
  { value: "19", label: "Bash" },
  { value: "20", label: "PowerShell" },
  { value: "21", label: "Git" },
  { value: "22", label: "GitHub" },
  { value: "23", label: "GitLab" },
  { value: "24", label: "Docker" },
  { value: "25", label: "Kubernetes" },
  { value: "26", label: "Jenkins" },
  { value: "27", label: "Travis CI" },
  { value: "28", label: "CircleCI" },
  { value: "29", label: "Ansible" },
  { value: "30", label: "Terraform" },
  { value: "31", label: "React.js" },
  { value: "32", label: "Angular" },
  { value: "33", label: "Vue.js" },
  { value: "34", label: "Node.js" },
  { value: "35", label: "Express.js" },
  { value: "36", label: "Django" },
  { value: "37", label: "Flask" },
  { value: "38", label: "Ruby on Rails" },
  { value: "39", label: "Spring" },
  { value: "40", label: "Laravel" },
  { value: "41", label: "ASP.NET" },
  { value: "42", label: "GraphQL" },
  { value: "43", label: "RESTful API" },
  { value: "44", label: "Redis" },
  { value: "45", label: "Elasticsearch" },
  { value: "46", label: "RabbitMQ" },
  { value: "47", label: "Kafka" },
  { value: "48", label: "TensorFlow" },
  { value: "49", label: "PyTorch" },
  { value: "50", label: "Keras" },
  { value: "51", label: "scikit-learn" },
  { value: "52", label: "Hadoop" },
  { value: "53", label: "Spark" },
  { value: "54", label: "JIRA" },
  { value: "55", label: "Trello" },
  { value: "56", label: "Slack" },
  { value: "57", label: "Figma" },
  { value: "58", label: "Sketch" },
  { value: "59", label: "Postman" },
  { value: "60", label: "Swagger" },
  { value: "61", label: "Selenium" },
  { value: "62", label: "JUnit" },
  { value: "63", label: "Mocha" },
  { value: "64", label: "Chai" },
  { value: "65", label: "Jest" },
  { value: "66", label: "NUnit" },
  { value: "67", label: "TestNG" },
  { value: "68", label: "Unreal Engine" },
  { value: "69", label: "Unity" },
  { value: "70", label: "Phaser 3" },
  { value: "71", label: "React Native" },
  { value: "72", label: "Flutter" },
  { value: "73", label: "Linux/Unix" },
  { value: "74", label: "CDN" },
  { value: "75", label: "Networking" },
  { value: "76", label: "Data Structure and Algorithms" },
  { value: "77", label: "Big Data" },
  { value: "78", label: "Micro-services" },
  { value: "79", label: "Cloud Computing" },

];
